import os
from snakemake.utils import min_version

WORKDIR = "/hlilab/gianfranco/pgtools/workflows/hmn_centromere"
configfile: os.path.join(WORKDIR, "config/config.yaml")
min_version(config["snakemake_min_version"])

DATADIR = config["fa_folder"]
sample_list = [l.strip() for l in open(config["sample_list_path"])]

wildcard_constraints:
    region = "centromeric|pericentromeric",
    chr = r"chr[0-9XYM]+"

include: "rules/prepare.smk"
include: "rules/cm.smk"
include: "rules/pcm.smk"

rule all:
    input:
        expand(
            os.path.join(WORKDIR, "results/snps/centromeres/{chr}/hmn462_unfilt.centromeric.snpmers.tsv"),
            chr=config["chroms"]
        ),
        expand(
            os.path.join(WORKDIR, "results/snps/centromeres/{chr}/hmn462_unfilt.centromeric.rare_kmers.tsv"),
            chr=config["chroms"]
        )
        # expand(
        #     os.path.join(WORKDIR, "results/snps/centromeres/{chr}/hmn462_unfilt.pericentromeric.{span}.vcf"),
        #     chr=config["chroms"],
        #     span=config["ranges"].keys()
        # )
        

# rule plot_umap:
#     input:
#         vcf = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/{chr}/hmn462_unfilt.vcf.gz"),
#         md_path = config["md_path"]
#     output:
#         plotdir = directory(os.path.join(WORKDIR, "plots/snps/centromeres/a_satellites/umap/{chr}"))
#     log:
#         "logs/snps/centromeres/a_satellites/{chr}/plot_umap_hmn462_unfilt.log"
#     conda:
#         "envs/py/ml.yaml"
#     script:
#         "scripts/py/plot_umap.py"

# rule plot_snps_density:
#     input:
#         vcf = lambda wildcards: expand(
#             os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/{chr}/hmn462_unfilt.vcf.gz"),
#             chr=discovered_chroms(wildcards)
#         ),
#         bed_dir = lambda wildcards: expand(
#             os.path.join(WORKDIR, "results/annotations/centromeres/a_satellites/add_sf/{chr}"),
#             chr=discovered_chroms(wildcards)
#         )
#     output:
#         plot = os.path.join(WORKDIR, "plots/snps/centromeres/a_satellites/stats/snp_density.png")
#     log:
#         "logs/snps/centromeres/a_satellites/plot_snps_density_hmn462_unfilt.log"
#     conda:
#         "envs/py/ml.yaml"
#     script:
#         "scripts/py/plot_stats.py"

# rule subset_genomes:
#     input:
#         fa_folder = config["fa_folder"],
#         bed_dir = os.path.join(WORKDIR, "data/annotations/centromeres/a_satellites")
#     output:
#         fa_folder = directory(os.path.join(WORKDIR, "results/fa_files/centromeres/a_satellites"))
#     threads:
#         config["bgzip_threads"]
#     log:
#         "logs/fa_files/centromeres/a_satellites/subset_fa_files.log"
#     conda:
#         "envs/standalone/sambedtools.yaml"
#     shell:
#         r"""
#         exec > {log} 2>&1
#         set -euo pipefail

#         mkdir -p {output.fa_folder}

#         for fa_file in {input.fa_folder}/*HG*.fa.gz {input.fa_folder}/*NA*.fa.gz; do
#             base=$(basename "$fa_file" .fa.gz)
#             case "$base" in *HG002*) continue ;; esac
#             bed={input.bed_dir}/"$base".as_hor_sf.bed
#             out={output.fa_folder}/"$base"_as.fa.gz

#             bgzip -cd -@ {threads} "$fa_file" > /tmp/"$base".fa
#             samtools faidx /tmp/"$base".fa

#             sort -k1,1 -k2,2n "$bed" \
#               | bedtools merge -i - \
#               | bedtools getfasta -fi /tmp/"$base".fa -bed - \
#               | bgzip -@ {threads} -c > "$out"

#             rm -f /tmp/"$base".fa /tmp/"$base".fa.fai
#         done
#         """

# rule ropebwt3_build_idx:
#     input:
#         fa_folder = os.path.join(WORKDIR, "results/fa_files/centromeres/a_satellites")
#     output:
#         bwt_fmr = os.path.join(WORKDIR, "data/ropebwt3_idx/hmn462_cm.fmr"),
#         bwt_fmd = os.path.join(WORKDIR, "data/ropebwt3_idx/hmn462_cm.fmd"),
#         bwt_ssa = os.path.join(WORKDIR, "data/ropebwt3_idx/hmn462_cm.fmd.ssa"),
#         bwt_len = os.path.join(WORKDIR, "data/ropebwt3_idx/hmn462_cm.fmd.len.gz")
#     log:
#         "logs/idx/ropebwt3_idx_hmn462.log"
#     threads:
#         config["ropebwt3_threads"]
#     conda:
#         "envs/standalone/ropebwt3.yaml"
#     shell:
#         """
#         ropebwt3 build -t{threads} -bo {output.bwt_fmr} $(ls {input.fa_folder}/*.fa.gz | grep -v '_HG002\.') 2> {log};
#         ropebwt3 build -i {output.bwt_fmr} -do {output.bwt_fmd} 2>> {log};
#         ropebwt3 ssa -o {output.bwt_ssa} -s8 -t{threads} {output.bwt_fmd} 2>> {log};
#         zcat $(ls {input.fa_folder}/*.fa.gz | grep -v '_HG002\.') | seqtk comp | cut -f1,2 | gzip > {output.bwt_len} 2>> {log}
#         """

# rule extract_snpmers:
#     input:
#         vcf = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.vcf.gz")
#     output:
#         snpmers = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.snpmers.tsv")
#     log:
#         "logs/snps/centromeres/a_satellites/extract_snpmers_hmn462_unfilt.log"
#     shell:
#         r"""
#         zcat {input.vcf} | awk -F'\t' -v OFS='\t' '!/^#/ {{
#             n = split($8, a, ";")
#             for (i = 1; i <= n; i++)
#                 if (a[i] ~ /^SNPMER=/) {{
#                     sub(/^SNPMER=/, "", a[i])
#                     print a[i], $4, $5
#                 }}
#         }}' > {output.snpmers} 2> {log}
#         """

# rule format_snpmers:
#     input:
#         snpmers = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.snpmers.tsv")
#     output:
#         snpmers = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.snpmers.fa")
#     log:
#         "logs/snps/centromeres/a_satellites/format_snpmers_hmn462_unfilt.log"
#     script:
#         "scripts/py/format_snpmers.py"
        

# rule compute_ropebwt3_hits:
#     input:
#         fmd_idx = os.path.join(WORKDIR, "data/ropebwt3_idx/human579.fmd"),
#         snpmers = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.snpmers.fa")
#     output:
#         hits = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.ropebwt3_hits.bed.gz")
#     params:
#         k = config["kmer_length"],
#         max_hits = 100
#     threads:
#         config["ropebwt3_threads"]
#     log:
#         "logs/snps/centromeres/a_satellites/compute_ropebwt3_hits_hmn462_unfilt.log"
#     conda:
#         "envs/standalone/ropebwt3.yaml"
#     shell:
#         """
#         ropebwt3 mem -t{threads} -l{params.k} -p{params.max_hits} {input.fmd_idx} {input.snpmers} 2> {log} | gzip > {output.hits}
#         """

# rule get_snps_info:
#     input:
#         hits = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.ropebwt3_hits.bed.gz"),
#         anno_table = os.path.join(WORKDIR, "results/annotations/anno_table.bed.gz"),
#         chrom_table = os.path.join(WORKDIR, "results/annotations/chromalias_table.txt")
#     output:
#         info = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.info.bed")
#     params:
#         k = config["kmer_length"],
#         threshold = 1
#     log:
#         "logs/snps/centromeres/a_satellites/get_snps_info_hmn462_unfilt.log"
#     conda:
#         "envs/py/pysam.yaml"
#     script:
#         "scripts/py/get_snps_info.py"

# rule filter_vcf:
#     input:
#         vcf = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.vcf.gz"),
#         info = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.info.bed")
#     output:
#         vcf = os.path.join(WORKDIR, "results/snps/centromeres/a_satellites/hmn462_unfilt.unambiguous.sorted.vcf.gz")
#     params:
#         script = os.path.join(WORKDIR, "scripts/py/filter_vcf.py")
#     log:
#         "logs/snps/centromeres/a_satellites/filter_vcf_hmn462_unfilt.log"
#     shell:
#         r"""
#         python {params.script} {input.vcf} {input.info} 2> {log} | bgzip > {output.vcf};
#         tabix -p vcf {output.vcf} 2>> {log}
#         """


# rule compute_clusters:
#     input:
#         vcf = os.path.join(WORKDIR, "results/snps/hmn579_unfilt.cleaned.sorted.{region}.vcf.gz"),
#         md_path = config["md_path"]
#     output:
#         md_path = os.path.join(WORKDIR, "results/clusters/hmn579_unfilt.cleaned.sorted.{region}.clusters.tsv")
#     params:
#         chroms = config["chroms"],
#         metrics = config["metrics"],
#         n_neighbors = 20,
#         n_components = 5,
#         random_seed = 42
#     log:
#         "logs/clusters/{region}/compute_clusters.log"
#     conda:
#         "envs/py/ml.yaml"
#     script:
#         "scripts/py/compute_clusters.py"